### ISSUE TITLE
Jackett & qBittorrent working fine, just not with each other

### ISSUE THREAD

**Issue by navjunk** [qbittorrent/search-plugins#164]
Hi, 

I have gone through issues #92, #121 but i dont have a solution yet. I have set it up on Linux Mint 20 (with Mono) and following are the details of environment and the issue:

1. qBittorrent 4.3.3 is working fine with rest of the search plugins i.e. excluding jackett. 
2. installed jackett at /opt/Jackett and it is working fine as a service and accessible at http://localhost:9117/. I am able to perform manual searches with selected indexes and able to download both magnet and regular torrent sourced from it using qBittorrent.
3. For qBittorrent, the jackett.json file is also at the path specified for Mint 20.x, which is different than location for Mint previous versions, as per the installing and configuration instructions for Mint 20.

However in qBittorrent, jackett itself is not listed as a search plugin and jackett searches still do not work/ appear in the search section. From the installation and configuring instructions for Jackett, I understand that Jackett is supposed to be enabled by default and can be disabled (successful search still dependent on the jackett.json file content and placement). While true for windows environment, I could not find the jackett appearing in search section/ plugins in qBitTorrent. **Pls guide.**

PS: Which version of qBittorrent started having Jackett internally by default?

**Comment by p060477** [comment]
i'm not able to use even jackett console...i have 0 results for a search about ubuntu... :(
![Immagine2](https://user-images.githubusercontent.com/12773559/111882721-5c919f80-89b7-11eb-85a2-df176bc6cec2.jpg)

se my #165 issue:
https://github.com/qbittorrent/search-plugins/issues/165

**Comment by navporky** [comment]
Have you chosen some appropriate indexes basis their type description?

**Comment by navjunk** [comment]
p060477, Have you configured any indexers? you need to before performing any search else it is searching nowhere.

**Comment by p060477** [comment]
done!
now it works!
but is there the only option  of -manual search-..??
thxs for yr helping!
cheers!

**Comment by navjunk** [comment]
I am not sure if I follow your query but if you mean that manual search in Jackett is working but jackett search is not working in qBittorrent (in windows) then, you need to create and place the jackett.json file in the nova engines folder. Follow instructions here: [configuring jackett](https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin)

**Comment by p060477** [comment]
thxs so 
much i'm continuing there

**Comment by jmayer004** [comment]
One thing to watch is "your_api_key" You need the Quotes on each side of it.

**Comment by ben2talk** [comment]
{
    "api_key": "igbsc00000000000000lfm1ymx0t",
    "tracker_first": true,
    "url": "http://127.0.0.1:9117"
}

API selected and pasted from the Jackett page http://127.0.0.1:9117/UI/Dashboard#
Yet still not workingi in mine...

Where is this 'main post'?

**Comment by navjunk** [comment]
> One thing to watch is "your_api_key" You need the Quotes on each side of it.

I understand. The quotes are present on both sides. My issue is that Jackett as a plugin does not appear in qBittorrent, which seems to be the case with a few other linux related recent posts, who are getting API key error. I will get to the stage of the API Key error only if qBittorrent shows up the Jackett plugin, which tries to read the json file.

**Comment by ngosang** [comment]
Jackett plugin is available since long time ago, like 2 years. I recommend you to update qBittorrent to a recent version.
You can check if the plugin is installed but it's disabled here:
![image](https://user-images.githubusercontent.com/10577978/118399085-b8953f00-b65b-11eb-9947-a4705623cb38.png)

If it's not available I think you can try to install the plugin manually. Use this URL => https://raw.githubusercontent.com/qbittorrent/search-plugins/master/nova3/engines/jackett.py
![image](https://user-images.githubusercontent.com/10577978/118399121-e084a280-b65b-11eb-9346-166c56eef69c.png)

**Comment by navjunk** [comment]
Thanks. Manual installation solved the issue instantaneously. Cheers.
